### ISSUE TITLE
Seperate external code

### ISSUE THREAD

**Issue by alyssarosenzweig** [christinaa/rpi-open-firmware#28]
At the moment, several external libraries are included within our codebase (in particular, libfdt and fatfs, in addition to the Broadcom headers). This is problematic from a maintenance standpoint (as it creates difficulties staying up-to-date), from a usability standpoint (as it bloats the size of the repository itself), and potentially from a licensing standpoint (already there is confusion regarding the Broadcom code). At a minimum, libfdt should be installed from the system package manager; it is unclear what the best course of action for the other two packages would be.

**Comment by christinaa** [comment]
I don't see a point in separating the external code. Besides it gives us an opportunity to customize and slim down libfdt depending on what we use. We also don't want to rely on system package managers and also want to ensure we have a specific version of it that we're using. In terms of licensing, it's BSD licensed so it's not a problem. Later when/if we have a 2nd stage loader, libfdt may be there instead of first stage. 

Fatfs should stay, we can't move it to 2nd stage since we need it to load stuff, and it requires customization so again, there is no problem with it. Fatfs is public domain so no licensing issues again.

Headers should stay, no question about it at all, they're a part of the codebase and are used by virtually every part of it, they're by no means bloat. I'm heavily against anything from "system package managers" because Linux is a clusterfuck and people run fuck knows what, including MOSX or WSL.

Closing this issue.
